# Generated by Django 3.1.4 on 2020-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_auto_20201217_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_ticket',
            name='flight_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
