# Generated by Django 3.1.4 on 2020-12-17 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_flight_ticket_flight_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_ticket',
            name='datetime_from',
        ),
        migrations.AddField(
            model_name='flight_ticket',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight_ticket',
            name='time_from',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
