# Generated by Django 3.1.4 on 2020-12-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_auto_20201217_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_ticket',
            name='code',
            field=models.TextField(default='AAAAA'),
            preserve_default=False,
        ),
    ]
