# Generated by Django 3.1.4 on 2020-12-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_flight_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_ticket',
            name='code',
            field=models.TextField(unique=True),
        ),
    ]
