# Generated by Django 3.1.4 on 2020-12-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_auto_20201218_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_ticket',
            name='to_booked',
            field=models.BooleanField(default=False),
        ),
    ]
